
  CREATE TABLE "AKVARYUM"."AKVARYUM_BALIK_BILGILERI" 
   (	"AKVARYUM_BALIK_TURU" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"AKVARYUM_BALIK_KATEGORI" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"AKVARYUM_BALIK_ID" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "AKVARYUM"."BALIK_DETAY" 
   (	"BALIK_KODU" NUMBER NOT NULL ENABLE, 
	"BALIK_ADI" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"URETICI_KODU" NUMBER, 
	"BALIK_TUR_KODU" NUMBER, 
	"DAVRANIS_KODU" NUMBER, 
	 CONSTRAINT "BALIK_DETAY_PK" PRIMARY KEY ("BALIK_KODU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



  CREATE TABLE "AKVARYUM"."BALIK_TURLERI" 
   (	"BALIK_TUR_KODU" NUMBER NOT NULL ENABLE, 
	"BALIK_TURU" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "AKVARYUM"."DAVRANIS" 
   (	"DAVRANIS_KODU" NUMBER NOT NULL ENABLE, 
	"DAVRANIS_TIPI" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "AKVARYUM"."DAVRANISLAR_PK" ON "AKVARYUM"."DAVRANIS" ("DAVRANIS_KODU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "AKVARYUM"."KATEGORI_BILGILERI" 
   (	"URETICI_KOD" NUMBER NOT NULL ENABLE, 
	"KATEGORI_ADI" VARCHAR2(60 BYTE), 
	 CONSTRAINT "URETICI_BILGILERI_PK" PRIMARY KEY ("URETICI_KOD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "AKVARYUM"."MUSTERI" 
   (	"MST_ID" NUMBER NOT NULL ENABLE, 
	"MST_AD" VARCHAR2(20 BYTE), 
	"MST_SOYAD" VARCHAR2(20 BYTE), 
	"MST_TELEFON" VARCHAR2(20 BYTE), 
	"MST_TC" VARCHAR2(20 BYTE), 
	"MST_SIFRE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "MUSTERI_PK" PRIMARY KEY ("MST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER "AKVARYUM"."MST_ID_INC" 
BEFORE INSERT ON AKVARYUM.MUSTERI
FOR EACH ROW
BEGIN
 SELECT MST_ID_INC.NEXTVAL
 INTO :NEW.MST_ID
 FROM DUAL;
 END;
/
ALTER TRIGGER "AKVARYUM"."MST_ID_INC" ENABLE;


  CREATE TABLE "AKVARYUM"."PER_KIMLIK_BILGILERI" 
   (	"PER_TC_NO" NUMBER(11,0), 
	"PER_SIFRE" NUMBER NOT NULL ENABLE, 
	"PER_KULLANICI_ADI" VARCHAR2(30 BYTE), 
	"PER_KULLANICI_SOYADI" VARCHAR2(30 BYTE), 
	 PRIMARY KEY ("PER_TC_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
