
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Giris_Ekrani extends javax.swing.JFrame {

    /**
     * Creates new form Giris_Ekrani
     */
    public Giris_Ekrani() {
        initComponents();
        
        setTitle("Giriş Ekranı");
        
        
        Toolkit toolkit = getToolkit();
        Dimension dim = toolkit.getScreenSize();
        setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        tc_label = new javax.swing.JLabel();
        sifre_label = new javax.swing.JLabel();
        tc_field = new javax.swing.JTextField();
        sifre_field = new javax.swing.JTextField();
        giris_buton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 240, 22));
        jPanel1.setLayout(null);

        tc_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tc_label.setForeground(new java.awt.Color(0, 255, 204));
        tc_label.setText("Tc");
        jPanel1.add(tc_label);
        tc_label.setBounds(170, 170, 60, 30);

        sifre_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sifre_label.setForeground(new java.awt.Color(0, 255, 204));
        sifre_label.setText("Şifre");
        jPanel1.add(sifre_label);
        sifre_label.setBounds(160, 240, 80, 29);

        tc_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tc_fieldKeyTyped(evt);
            }
        });
        jPanel1.add(tc_field);
        tc_field.setBounds(216, 175, 160, 30);

        sifre_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sifre_fieldKeyTyped(evt);
            }
        });
        jPanel1.add(sifre_field);
        sifre_field.setBounds(216, 236, 160, 30);

        giris_buton.setText("Giriş Yap");
        giris_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_butonActionPerformed(evt);
            }
        });
        jPanel1.add(giris_buton);
        giris_buton.setBounds(230, 290, 130, 30);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(124, 100, 0, 0);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("AKVARYUM YÖNETİMİ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 110, 390, 44);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 115, 0, 0);

        jButton1.setText("Admin Girişi Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 340, 160, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\DERSLER\\veritabanı\\Adsız.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 610, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    Database_Connect islem = new Database_Connect();
        
    public Connection conn = islem.con;
    
    
    
    private void tc_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tc_fieldKeyTyped

        
        
        String metin = tc_field.getText();
        int uzunluk = metin.length();

        char karakter = evt.getKeyChar();
               
        
        
        if( !(Character.isDigit(karakter)) )
        {
            evt.consume();
        }
        
        if(uzunluk>=11)
        {
          evt.consume();
        }    
        
        
    }//GEN-LAST:event_tc_fieldKeyTyped

    private void sifre_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sifre_fieldKeyTyped
       
        String metin = sifre_field.getText();
        int uzunluk = metin.length();

        char karakter = evt.getKeyChar();
               
        
        
        if( !(Character.isDigit(karakter)) )
        {
            evt.consume();
        }
        
        if(uzunluk>=4)
        {
          evt.consume();
        }    
        
        
    }//GEN-LAST:event_sifre_fieldKeyTyped

    private void giris_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_butonActionPerformed
        
        
        
        String tc=tc_field.getText();
        String sifre=sifre_field.getText();
        
        int tc_uzunluk=tc.length();
        
        int sifre_uzunluk=sifre.length();
        
        
        if(tc_uzunluk!=11 || sifre_uzunluk!=4)
        {
            JOptionPane.showMessageDialog(this,"Tc kimlik numaranızı veya şifrenizi eksik tuşladınız!","UYARI",JOptionPane.WARNING_MESSAGE);
            
            return;
        }
        
        
        boolean giris_kontrol=GirisYapTc(tc,sifre);
        
     
        if(!(giris_kontrol))
        {
            
           JOptionPane.showMessageDialog(this,"Sistemde böyle bir kullanıcı bulunmamaktadır!","UYARI",JOptionPane.WARNING_MESSAGE);
            
           return; 
            
        }    
        
        balik_islem_ekrani ekran = new balik_islem_ekrani();
        
        this.dispose();
        
        ekran.setVisible(true);
        
    }//GEN-LAST:event_giris_butonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String tc=tc_field.getText();
        String sifre=sifre_field.getText();
        
        int tc_uzunluk=tc.length();
        
        int sifre_uzunluk=sifre.length();
        
        
        if(tc_uzunluk!=11 || sifre_uzunluk!=4)
        {
            JOptionPane.showMessageDialog(this,"Tc kimlik numaranızı veya şifrenizi eksik tuşladınız!","UYARI",JOptionPane.WARNING_MESSAGE);
            
            return;
        }
        
        
        boolean giris_kontrol=GirisYapAdmin(tc,sifre);
        
     
        if(!(giris_kontrol))
        {
            
           JOptionPane.showMessageDialog(this,"Sistemde böyle bir kullanıcı bulunmamaktadır!","UYARI",JOptionPane.WARNING_MESSAGE);
            
           return; 
            
        }    
        
        admin_paneli ekran = new admin_paneli();
        
        this.dispose();
        
        ekran.setVisible(true);
        
                             
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public boolean GirisYapTc(String tc,String sifre)
    {
        
        String sorgu= " Select mst_tc,mst_sifre from "
                + "musteri"
                + " where mst_tc =? and mst_sifre=?";
        
        
        
        try
        {
            PreparedStatement st = conn.prepareStatement(sorgu);

           
            st.setString(1,tc); //Soru işareti yerine tc gönderiyoruz
            st.setString(2,sifre);
            
            ResultSet rs = st.executeQuery();
            
           
            if(rs.next())
            {
                return true;
            }    
            
        } 
        
        
        
        catch (SQLException ex)
        {
             Logger.getLogger(Giris_Ekrani.class.getName()).log(Level.SEVERE, null, ex);
             
        }
        
        return false;
        
    }
    
        public boolean GirisYapAdmin(String tc,String sifre)
    {
        
        String sorgu= " Select per_tc_no,per_sifre from "
                + "per_kimlik_bilgileri"
                + " where per_tc_no =? and per_sifre=?";
        
        
        
        try
        {
            PreparedStatement st = conn.prepareStatement(sorgu);

           
            st.setString(1,tc); //Soru işareti yerine tc gönderiyoruz
            st.setString(2,sifre);
            
            ResultSet rs = st.executeQuery();
            
           
            if(rs.next())
            {
                return true;
            }    
            
        } 
        
        
        
        catch (SQLException ex)
        {
             Logger.getLogger(Giris_Ekrani.class.getName()).log(Level.SEVERE, null, ex);
             
        }
        
        return false;
        
    }
    
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris_Ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton giris_buton;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sifre_field;
    private javax.swing.JLabel sifre_label;
    private javax.swing.JTextField tc_field;
    private javax.swing.JLabel tc_label;
    // End of variables declaration//GEN-END:variables
}
