
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nahit
 */
public class Kategoriler extends javax.swing.JFrame {

    
    public Object item = null;
    
    
     public Statement statement = null;
    
     public PreparedStatement preparedstatement= null;
     
     public  ResultSet resultset = null;
     
     Database_Connect islem = new Database_Connect();
        
     public Connection conn = islem.con;
    
    /**
     * Creates new form Kategoriler
     */
    public Kategoriler() {
        initComponents();
        
                 Toolkit toolkit = getToolkit();
        Dimension dim = toolkit.getScreenSize();
        setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setTitle("Kategori Ekranı");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uretici_kodu_field = new javax.swing.JTextField();
        uretici_adi_field = new javax.swing.JTextField();
        ekle_buton = new javax.swing.JButton();
        guncelle_buton = new javax.swing.JButton();
        sil_buton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        getir_buton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kategori Kodu");

        jLabel2.setText("Kategori Adı");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, uretici_adi_field, org.jdesktop.beansbinding.ObjectProperty.create(), uretici_kodu_field, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        uretici_kodu_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uretici_kodu_fieldActionPerformed(evt);
            }
        });
        uretici_kodu_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uretici_kodu_fieldKeyTyped(evt);
            }
        });

        uretici_adi_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uretici_adi_fieldKeyTyped(evt);
            }
        });

        ekle_buton.setText("Ekle");
        ekle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_butonActionPerformed(evt);
            }
        });

        guncelle_buton.setText("Güncelle");
        guncelle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_butonActionPerformed(evt);
            }
        });

        sil_buton.setText("Sil");
        sil_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonActionPerformed(evt);
            }
        });

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kategori Kodu", "Kategorii Adi"
            }
        ));
        jScrollPane1.setViewportView(tablo);

        getir_buton.setText("Getir");
        getir_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getir_butonActionPerformed(evt);
            }
        });

        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(ekle_buton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(uretici_adi_field, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uretici_kodu_field, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(getir_buton)
                                    .addComponent(guncelle_buton)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addComponent(sil_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel4)))
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(uretici_kodu_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(uretici_adi_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ekle_buton)
                            .addComponent(guncelle_buton)
                            .addComponent(sil_buton))
                        .addGap(38, 38, 38)
                        .addComponent(getir_buton)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uretici_kodu_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uretici_kodu_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uretici_kodu_fieldActionPerformed

    private void guncelle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_butonActionPerformed

        String uretici_kodu=uretici_kodu_field.getText();
        String kategori_adi=uretici_adi_field.getText().toUpperCase();
        
        if(uretici_kodu.equals(""))
        {
            
             JOptionPane.showMessageDialog(this, "Kategori kodu boş geçilemez!","UYARI",JOptionPane.WARNING_MESSAGE);

             uretici_kodu_field.requestFocus();

             return;
            
        }
        
        boolean kontrol=kod_kontrol(uretici_kodu);
        
        if(kontrol==false)
        {
           JOptionPane.showMessageDialog(this, "Böyle bir kategori kodu kayıtlarda bulunmamaktadır!","UYARI",JOptionPane.WARNING_MESSAGE); 
           
           uretici_kodu_field.requestFocus();
           
           return;
           
        }
        
        try
        {
            
            
            preparedstatement=conn.prepareStatement(
                    "UPDATE kategori_bilgileri"
                            + " SET  kategori_adi= ?"
                            + " WHERE uretici_kod=?");
            
            preparedstatement.setString(1,kategori_adi);
            preparedstatement.setString(2,uretici_kodu);
            
            
            preparedstatement.execute();
        }
        
        catch (SQLException ex) 
        {
            Logger.getLogger(Kategoriler.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        
        
        JOptionPane.showMessageDialog(this,"Kayit Başarıyla Güncellendi!");
        
        uretici_adi_field.setText("");
        uretici_kodu_field.setText("");
        
        
    }//GEN-LAST:event_guncelle_butonActionPerformed

    private void sil_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonActionPerformed


        String uretici_kodu=uretici_kodu_field.getText();
        
        if(uretici_kodu.equals(""))
        {
            
             JOptionPane.showMessageDialog(this, "Kategori kodu boş geçilemez!","UYARI",JOptionPane.WARNING_MESSAGE);

             uretici_kodu_field.requestFocus();

             return;
            
        }
        
        boolean kontrol=kod_kontrol(uretici_kodu);
        
        if(kontrol==false)
        {
           JOptionPane.showMessageDialog(this, "Böyle bir Kategori kodu kayıtlarda bulunmamaktadır!","UYARI",JOptionPane.WARNING_MESSAGE); 
           
           uretici_kodu_field.requestFocus();
           
           return;
           
        }
        
       try
        {
            
            
            preparedstatement=conn.prepareStatement(
                    "DELETE FROM kategori_bilgileri"
                            + " WHERE uretici_kod=?");
            
            preparedstatement.setString(1,uretici_kodu);
            
            preparedstatement.execute();
        }
        
        catch (SQLException ex) 
        {
            
           String fk_kontol = ex.getMessage();
            
           if(fk_kontol.contains("FK"));   //Foreign Key Hatası
           JOptionPane.showMessageDialog(this, "Silmeye çalıştığınız Kategori kodu ilaç tanım tablosunda bulunmaktadır, silemezsiniz!!","UYARI",JOptionPane.WARNING_MESSAGE);
           
           return;
           
            
        }
        
      
        JOptionPane.showMessageDialog(this,"Kayit Başarıyla Silindi"); 
        
        uretici_adi_field.setText("");
        uretici_kodu_field.setText("");
        
        
    }//GEN-LAST:event_sil_butonActionPerformed

    private void getir_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getir_butonActionPerformed
        
        DefaultTableModel model = (DefaultTableModel)tablo.getModel();
        
        model.setRowCount(0);
        
        String sorgu = " Select uretici_kod,kategori_adi From kategori_bilgileri order by uretici_kod";

        String uretici_kodu;
        String uretici;
        
        
        
        try
        {
            
            statement=conn.createStatement();
            
            resultset = statement.executeQuery(sorgu);
            
            while(resultset.next())
            {
             
               uretici_kodu=resultset.getString("uretici_kod");
               uretici=resultset.getString("kategori_adi");
               
               Object [] eklenecek = {uretici_kodu,uretici};
               
               model.addRow(eklenecek);
            
                
            }
            
            resultset.close();
            
        }
                       
       
         
         catch (SQLException ex) 
         {
             
           ex.printStackTrace();
           return;
                  
         }
        
    }//GEN-LAST:event_getir_butonActionPerformed

    private void ekle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_butonActionPerformed
       
        String uretici_kodu=uretici_kodu_field.getText().toUpperCase();
        String kategori_adi=uretici_adi_field.getText().toUpperCase();
        
        String sorgu = " insert into kategori_bilgileri"
                 + " (uretici_kod,kategori_adi)"
                 + " values (?, ?)";
        
        
        try
        {

            preparedstatement=conn.prepareStatement(sorgu);

            preparedstatement.setString(1,uretici_kodu);
            preparedstatement.setString(2,kategori_adi);

            preparedstatement.execute();

        }
                       
       
         
         catch (SQLException ex) 
         {
             
            String hata_mesajı = ex.getMessage();
            
            boolean pk_kontrol = hata_mesajı.contains("PK");    //Primary Key
             
            boolean null_kontrol = hata_mesajı.contains("NULL");

            if(pk_kontrol == true)
            {
             JOptionPane.showMessageDialog(this, "Girdiğiniz Kategori kodu kayitlarda mevcuttur!","UYARI",JOptionPane.WARNING_MESSAGE);

             uretici_kodu_field.requestFocus();

             return;
            }
            
            else if (null_kontrol)
            {
               
             JOptionPane.showMessageDialog(this, "Kategori kodu boş geçilemez!","UYARI",JOptionPane.WARNING_MESSAGE);

             uretici_kodu_field.requestFocus();

             return;
                       
            }
                  
         }
         
        JOptionPane.showMessageDialog(this,"Kayit Başarıyla Eklendi!");
        
        uretici_adi_field.setText("");
        uretici_kodu_field.setText("");
        
        
    }//GEN-LAST:event_ekle_butonActionPerformed

    private void uretici_kodu_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uretici_kodu_fieldKeyTyped
       
        String metin = uretici_kodu_field.getText();
        int uzunluk = metin.length();
        
        char karakter = evt.getKeyChar();
    
        if( !(Character.isDigit(karakter)) || uzunluk == 4 )
        {
         evt.consume();
        }
        
    }//GEN-LAST:event_uretici_kodu_fieldKeyTyped

    private void uretici_adi_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uretici_adi_fieldKeyTyped
        
        
        char karakter = evt.getKeyChar();
    
        if( (Character.isDigit(karakter)))
        {
         evt.consume();
        } 
        
        
    }//GEN-LAST:event_uretici_adi_fieldKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.dispose();
        balik_islem_ekrani ekran = new balik_islem_ekrani();
        ekran.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean kod_kontrol(String kod)
    {
        
        String sorgu= " Select uretici_kod from "
                + "kategori_bilgileri"
                + " where uretici_kod=?";
        
        
        
        try
        {
            PreparedStatement st = conn.prepareStatement(sorgu);

           
            st.setString(1,kod); //Soru işareti yerine tc gönderiyoruz
           
            ResultSet rs = st.executeQuery();
            
           
            if(rs.next())
            {
                return true;
            }    
            
        } 
        
        
        
        catch (SQLException ex)
        {
             Logger.getLogger(Giris_Ekrani.class.getName()).log(Level.SEVERE, null, ex);
             
        }
        
        return false;
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kategoriler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kategoriler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kategoriler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kategoriler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kategoriler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ekle_buton;
    private javax.swing.JButton getir_buton;
    private javax.swing.JButton guncelle_buton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sil_buton;
    private javax.swing.JTable tablo;
    private javax.swing.JTextField uretici_adi_field;
    private javax.swing.JTextField uretici_kodu_field;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
